# Generated by Django 4.0.4 on 2022-05-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudwareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(max_length=500, upload_to='cloudwareApp/media/'),
        ),
    ]
