# Generated by Django 4.0.4 on 2022-04-26 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloudwareApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareDirectory',
            new_name='SharedDirectory',
        ),
        migrations.RenameModel(
            old_name='ShareFile',
            new_name='SharedFile',
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name_plural': 'Directories'},
        ),
        migrations.AlterModelOptions(
            name='shareddirectory',
            options={'verbose_name_plural': 'Shared Directories'},
        ),
    ]
