# Generated by Django 4.0.4 on 2022-05-02 22:33

import cloudwareApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudwareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(upload_to=cloudwareApp.models.content_file_name),
        ),
    ]
