# Generated by Django 4.0.4 on 2022-04-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudwareApp', '0003_file_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploadedFile',
            new_name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
